baseURL = 'https://pbund.github.io/blog2/'
languageCode = 'en-us'
title = 'Grokking Cisco with Marty Bullfrog'
theme = 'm10c'

[params]
  author = "Paul Bundschuh"
  description = "Blogs about Cisco networking and other technical topics"

