baseURL = 'https://pbund.github.io/blog2/'
languageCode = 'en-us'
title = 'Blog2 by Marty Bullfrog'
theme = 'm10c'

[params]
  author = "Paul Bundschuh"
  description = "A blog about all things technical."

